language: go
go:
  - 1.1.2
  - 1.2
  - release
  - tip
install:
  - script/build
script: script/test
before_script:
  - psql -c 'create database ddocus_test;' -U postgres

matrix:
  allow_failures:
    - go: release
    - go: tip
